### ISSUE TITLE
How can I remove the max 2 upload limit per week?

### ISSUE THREAD

**Issue by Troplo** [Silinator/We-TeVe#1]
I'd like to know how I can remove the 2 week upload limit.
Also, I see there is a /admin folder is it possible to make people admin in this?

**Comment by Silinator** [comment]
> I'd like to know how I can remove the 2 week upload limit.

With higher level you can upload more Videos per week. The first video you get at level 50 and the next on level 100 and so on.

> Also, I see there is a /admin folder is it possible to make people admin in this?

Admins are only certain Accounts. And can't get set in the admin portal. The /admin portal is at the momant useless anyway. It was for coinhive, but we kind of removed this tool.

**Comment by Troplo** [comment]
Hi, thanks for the reply, I have found a few bugs, which I would like to report:

- Video views stuck at 0 for some reason
- Most folders don't auto-generate like the profile picture folder, or even the video upload folder.
- Trying to close the video when you are browsing other pages doesn't work: Console error: `Uncaught TypeError: The element or ID supplied is not valid. (videojs)
    at videojs$1 (<anonymous>:26466:13)
    at close_miniplayer (function.js:197)
    at HTMLDivElement.<anonymous> (function.js:165)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.q.handle (jquery.min.js:3)`

I think that's the only issues, other than that the script is running well and is stable

**Comment by Silinator** [comment]
Hi, thank you very much for your testing!

> Video views stuck at 0 for some reason

On your system? On the online system works it normal.

> Most folders don't auto-generate like the profile picture folder, or even the video upload folder.

What do you meen with auto-generate?

> I think that's the only issues, other than that the script is running well and is stable

There are more bugs for sure :D
